name: Bug Report
description: Report a problem with the portal CLI
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Please ensure you are using the latest version of `portal` before reporting.
  - type: textarea
    id: description
    attributes:
      label: What is the issue?
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: input
    id: command
    attributes:
      label: Command executed
      placeholder: "e.g., portal send ./data.txt"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Terminal Output
      description: Please copy and paste the full output, including any stack traces.
      render: shell
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - macOS
        - Linux
        - Windows (CMD/PowerShell)
        - Windows (WSL)
        - Andriod (Termux)
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Portal Version
      placeholder: "Run 'portal --version'"
    validations:
      required: true
