[package]
name = "pxp"
version = "0.1.0"
authors = ["Spectra010s"]
edition = "2024"
repository = "https://github.com/Spectra010s/portal"
description = "A consumer-agnostic Rust library implementation of the Portal Transfer Protocol (PXP)"
homepage = "https://github.com/Spectra010s/portal"
license = "MIT"

[lib]
name = "pxp"
path = "src/lib.rs"

[dependencies]
thiserror = "2"
serde = { version = "1.0.228", features = ["derive"] }
bincode = "1.3.3"
network-interface = "2.0.5"
tokio = { version = "1.49.0", features = ["full"] }
serde_json = "1.0.149"
socket2 = "0.6.2"
uuid = { version = "1.21.0", features = ["v4"] }
async-compression = { version = "0.4", features = ["tokio", "gzip"] }
astral-tokio-tar = "0.6.2"
tokio-stream = "0.1.18"
async-walkdir = "2.1.0"
tracing = { version = "0.1.44", features = ["log"] }
